# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [124]:
#1
import numpy as np

data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)

In [125]:
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [126]:
#2
print(np.mean(data[:, 1:], axis = 0)) #среднее значение
print(np.min(data[:, 1:], axis = 0)) #минимум
print(np.max(data[:, 1:], axis = 0)) #максимум
print(np.median(data[:, 1:], axis = 0)) #медиана


[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


In [127]:
#3
q75 = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.minimum(data[:, 1], q75)
print(data[-1:])

[[81993    65    14]]


In [128]:
#4
count = np.count_nonzero(data[:, 1] == 0)
if count > 0:
    data[:, 1] = np.where(data[:, 1] == 0, 1, data[:, 1])
print(count)

479


In [129]:
#5
un_rcps = np.unique(data[:, 0])
num_un_rcps = len(un_rcps)
print('Количество уникальных рецептов:', num_un_rcps)

Количество уникальных рецептов: 100000


In [130]:
#6
un_ing = np.unique(data[:, 2])
print(un_ing)
print('кол-во уникальных значений -', len(un_ing))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
кол-во уникальных значений - 37


In [131]:
#7
print(data[data[:, 2] <= 5]) 

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


In [132]:
#8
ing_per_min = data[:, 2] / data[:, 1]
print(np.max(ing_per_min))

24.0


In [133]:
#9
top100_rcps = data[np.argsort(data[:, 1])[::-1][:100]] #топ 100 рецептов по длительности
print(np.mean(top100_rcps[:, 2])) # среднее кол-во инг-тов среди топов


9.96


In [134]:
#10
random_rcps = np.random.choice(data.shape[0], 10, replace=False)
for id in random_rcps:
    r_id, time, ingrs = data[id]
    print(f'id рецепта: {r_id}, время выполнения: {time}, кол-во рецептов: {ingrs}')
    

id рецепта: 240135, время выполнения: 2, кол-во рецептов: 4
id рецепта: 309907, время выполнения: 35, кол-во рецептов: 10
id рецепта: 301484, время выполнения: 55, кол-во рецептов: 12
id рецепта: 92597, время выполнения: 40, кол-во рецептов: 10
id рецепта: 536747, время выполнения: 65, кол-во рецептов: 20
id рецепта: 146499, время выполнения: 15, кол-во рецептов: 9
id рецепта: 51459, время выполнения: 65, кол-во рецептов: 8
id рецепта: 111920, время выполнения: 50, кол-во рецептов: 13
id рецепта: 354023, время выполнения: 35, кол-во рецептов: 13
id рецепта: 415277, время выполнения: 65, кол-во рецептов: 9


In [135]:
#11
sr = np.mean(data[:, 2])
ings_mnsh_sr = data[data[:, 2] < sr]
print((len(ings_mnsh_sr) / len(data)) * 100) # в процентах 

58.802


In [136]:
#12
simp_rcp = ((data[:, 1] <= 20) & (data[:, 2] <= 5)).astype(int)

data_with_simp_cl = np.column_stack((data, simp_rcp))
print(data_with_simp_cl[:10])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]
 [152828     40      7      0]
 [ 33941     18      9      0]
 [446597     15      5      1]
 [366174      7      9      0]
 [ 74205     20      7      0]]


In [137]:
#13
print(np.mean(simp_rcp) * 100, '%')

9.552 %


In [138]:
#14
short_rcps = data[data[:, 1] < 10]
standard_rcps = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long_rcps = data[data[:, 1] >= 20]

max_len = min(len(short_rcps), len(standard_rcps), len(long_rcps)) #максимальное кол-во рецептов в каждой группе

grouped_recipes = np.zeros((3, max_len, 3), dtype=int)
grouped_recipes[0, :len(short_rcps[:max_len])] = short_rcps[:max_len]
grouped_recipes[1, :len(standard_rcps[:max_len])] = standard_rcps[:max_len]
grouped_recipes[2, :len(long_rcps[:max_len])] = long_rcps[:max_len]

print(grouped_recipes)
print(grouped_recipes.shape)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      1      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
(3, 7588, 3)
